// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentDetail.Data;

namespace PaymentDetail.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20211022004446_Inital Add")]
    partial class InitalAdd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("PaymentDetail.Models.PaymentDetailModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("cardNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("cardOwnerName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("expirationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("securityCode")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("tb_payment_detail");
                });
#pragma warning restore 612, 618
        }
    }
}
